services:
  - type: web
    name: waritaro
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false   # Render ダッシュボードで config/master.key の内容を手動設定
      - key: DATABASE_URL
        fromDatabase:
          name: waritaro-db
          property: connectionString
      - key: RAILS_LOG_LEVEL
        value: info

databases:
  - name: waritaro-db
    databaseName: waritaro_production
    plan: free
